name: CI/CD for PyQt6 App

on:
  push:
    branches:
      - main
      - macos
      - windows
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]  # Only macOS and Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upgrade pip and install wheel
      run: |
        pip install --upgrade pip setuptools wheel

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
      timeout-minutes: 10  # Extend timeout

    - name: Run tests
      run: |
        pytest
    
    - name: Build Application
      run: |
        pip install pyinstaller
        pyinstaller --onefile main.py
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PyQt6-Build
        path: dist/
